[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "container-registry-cleanup"
version = "0.0.1"
description = "Github Action for container registry cleanup."
requires-python = ">=3.11"

[tool.setuptools]
py-modules = ["cleanup_container_registry"]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
